apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: os53a122m-go 
  janus-idp.io/tekton: os53a122m-go
  backstage.io/kubernetes-id: os53a122m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: os53a122m-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  