apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: os53a122m-go-gitops
  description: This is GitOps manifest for os53a122m-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=os53a122m-go
    backstage.io/kubernetes-id: os53a122m-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: os53a122m-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:os53a122m-go
